import React from 'react';
import FeatureItem from '../../components/common/FeatureItem';
import SectionHeader from '../../components/common/SectionHeader';
import SectionLayout from '../../layouts/SectionLayout';

const altradySubscribeData = [
  {
    title: `Altrady helps you get better profits, consistently.`,
    features: [
      {
        content: `More than 90% of cryptocurrency traders fail and lose money. They say that it’s because of volatile markets and rash decisions. Whatever it is, we don’t want to witness another failure.`
      },
      {
        content: `We don’t promise you heavens — but we promise to help you win trades, get better profits, and build your assets consistently.`
      },
      {
        content: `We do this by equipping you with the right tools like Base Scanner and Quick Scanner so you can create a sense of predictability in market movements and make the right trading decisions for better profits.`
      }
    ]
  },
  {
    title: `Altrady lets you save time, so you can do other things.`,
    features: [
      {
        content: `Majority of traders say that crypto trading is toxic and time-consuming.`
      },
      {
        content: `With Altrady, we hope to give you a better chance of having a fulfilling life — a life that is not isolated from the real world.`
      },
      {
        content: `Features like real-time crypto alerts and automated trading lets you monitor markets and trade crypto even when you are asleep or spending time with family.`
      }
    ]
  },
  {
    title: `Altrady makes trading simple, for your convenience.`,
    features: [
      {
        content: `Trading on different exchanges is complicated, confusing, and overwhelming.`
      },
      {
        content: `Altrady simplifies the process by giving you an all-in-one platform where you can trade, monitor markets, and manage assets across different exchanges.`
      },
      {
        content: `Use Altrady’s trading terminal to buy and sell crypto on multiple exchanges using only the Altrady app.`
      },
      {
        content: `Use Altrady’s portfolio manager to see the growth of your assets in different exchange wallets.`
      }
    ]
  },
  {
    title: `Altrady gives accurate information, so you can make objective trading decisions.`,
    features: [
      {
        content: `Emotions can get in the way of strategic trading — it can easily make you excited, panicky, and fearful.`
      },
      {
        content: `Altrady’s powerful crypto signals are generated by unique algorithms that are not influenced by random emotions.`
      },
      {
        content: `Altrady neutralizes trading emotions so you can make strategic and objective trading decisions.`
      }
    ]
  },
  {
    title: `Altrady equips you with powerful tools, so you can grow in experience and expertise.`,
    features: [
      {
        content: `More than 80% of new traders quit in the first two years. With a lot of challenges, quitting can be easily done.`
      },
      {
        content: `Although trading is a learning process, we can’t afford to just lose all the time.`
      },
      {
        content: `Altrady helps you learn and grow with a minimum risk and with maximum potentials.`
      },
      {
        content: `Through Altrady’s innovative trading tools, you can grow as a crypto trader who can efficiently use the available technology to his or her advantage.`
      }
    ]
  }
]

const AltradySubscribeListSection = ({title, content}) => {
  return (
    <SectionLayout sectionName="altrady-subscribe">
      <SectionHeader
        title={title}
        content={content} />
      <div className="cryptor-content-wrapper">
        {altradySubscribeData.map( (item, idx) => <FeatureItem 
          key={idx}
          even={(idx % 2 === 0) ? "" : " flex-row-reverse"}
          {...item} />)}
      </div>
    </SectionLayout>
  );
};

export default AltradySubscribeListSection;